---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor 
spec:
  type: NodePort
  selector:
    app: monitor 
  ports:
  - protocol: TCP
    port: 5000
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: emirhanmetin/py-flask:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1

